### ISSUE TITLE
Error related to non-squared matrices in 'eigen'

### ISSUE THREAD

**Issue by ggrittz** [pasraia/RRdtn#1]
Hello, 

I've been using the ENphylo from your MEE paper and unfortunately got the following error:
```
**Error in { : task 1 failed - "matriz não quadrada em 'eigen'"
In addition: Warning messages:
1: In ENphylo_modeling(input_data = all_list_cleaned, tree = tree,  :
  The number of species with occurrences below min_occ_enfa exceeds the 30% of total species.
                      min_occ_enfa value was reduced to 1**
```
 
There are some other minimal warning messages related to dir.create() but I don't think they are relevant for the issue in question. I imagine the (1) warning is also not relevant. 

The translation is something like a "non-squared matrix in 'eigen'. Any idea? 

Some info about my data: 659 species; the phylogenetic tree is ok; 60% of my species have less than 20 occurrences.

This is my function input:
```
raremod <- ENphylo_modeling(input_data = all_list_cleaned,
                            tree = tree,
                            input_mask = stack(preds),
                            obs_col = "occurrence",
                            min_occ_enfa = 20, #I also tried to use 10, but the same error keeps occurring
                            boot_test_perc = 20,
                            boot_reps = 100,
                            eval_metric_for_imputation = "AUC",
                            output_options = "best",
                            clust = 6,
                            eval_threshold = 0.5)
```

Thanks already

EDIT: I have all the .rds files here. I'll upload it here soon.

**Comment by pasraia** [comment]
Hi Guilherme,
Thanks for sharing the data. We tried to run ENphylo_modeling by using your species data and maps. Unfortunately, there are some issues with the data. First, ENphylo was tested imputing up to 30% of the species simultaneously. Going beyond this limit is theoretically possible but not advisable. More importantly, the function is instructed to modify min_occ_enfa until 70% of the species can be modeled with ENFA. In your case, since the percentage of species to impute you’re trying to work with (60%) is very high, min_occ_enfa=20 (your setting) reduces to 2, which makes the evaluation step impossible to perform. 
There are possible workarounds. You may want to remove species with less than 5 occurrences. This also avoids the risk to have an entire clade on the tree to impute. Alternatively, you can try to run ENphylo_modeling without performing the evaluation step by selecting boot_rep argument equal to 0. However, please consider performing validation with less than 10 occurrences is far from ideal.
A second minor issue is the structure of input mask object. It should be a simple raster layer not a stack. The function only uses the extent and resolution of mask. Consequently, it is not important to provide all raster variables.
I would like to thank you to test ENphylo. I hope our advice will help. 
 
Kind regards

**Comment by ggrittz** [comment]
Thank you for your quick reply! I'll definitely take a look at your recommendation and give feedback asap.

**Comment by ggrittz** [comment]
Hello again

As suggested, I applied some changes to my data. I removed species with less than 10 occurrences. Now I'm only imputing around 23% of the species (those between 10 and 20 occurrences). This solves the aforementioned issue. Here are the new parameters and how I'm loading the data:

```
#Loading presence-background list
all_list <- readRDS("rds/all_list.rds")

#Loading predictors' extent/mask
preds <- list.files("output/", pattern = ".tif", full.names = TRUE)
preds <- stack(rast(preds)) #the file I attached is simply the rast(preds) output

#Loading phylogenetic tree
tree <- ape::read.tree("sample.tre")

#Modeling
raremod <- ENphylo_modeling(input_data = all_list,
                            tree = tree,
                            input_mask = preds[[1]],
                            obs_col = "occurrence",
                            min_occ_enfa = 20,
                            boot_test_perc = 20,
                            boot_reps = 0,
                            eval_metric_for_imputation = "AUC",
                            output_options = "best",
                            clust = 4,
                            eval_threshold = 0.5)
```

But now the following error occurs: 

```
Error in crossprod(Sm, DpSm) : non-conformable arguments
```
And the following ```warnings()```

```
In x * p : longer object length is not a multiple of shorter object length
```
Some species are modeled before the error. The error always occurs on the 11 species (Alchornea_triplinervia), but the data of it seems ok.

As far as I can tell, the error and warnings are related to matrices multiplication, right?

Here's the new data for reproduction: https://drive.google.com/drive/folders/1Hz91FqoyPvP8HWq62AOtq_PCe9AsEnAy?usp=share_link

Thank you already,

Cheers

**Comment by ggrittz** [comment]
(I should have opened another issue, sorry — if anything we can move it later I think)

**Comment by pasraia** [comment]
Hi Guilherme, 

We ran ENphylo by using your data.  The issue is not related to species sample size at this time. Instead, please notice multiple Alchornea triplinervia datapoints fall in the same raster cell. Since multiple observations per cells are pseudoreplicates, you should always collapse them in a single occurrence (this is true of any SDM you apply). In this particular case, the matrix crossproduct is impossible because the number of cells for this particular species (167) is matched by 168 datapoints. Consequently, the ENFA matrix estimation fails.

 
Alessandro Mondanaro preparad  a little script (few lines) to let you check on yoruself:

subset(all_list [[11]],occurrence==1)$geometry->ones ### select Alchornea triplinervia datapoints

as(ones,"Spatial")->ones ### convert sf to sp object

duplicated(extract(raster(predictors_raster[[1]]),ones,cellnumbers=TRUE)[,1])

## cell 4744 is duplicated

 
As a further advice, please notice in the current version ENphylo relies on the “raster” R package. It does not work with SpatRaster. However, we are preparing a new version of our package to account for "terra". Lastly, if you select "boot_rep=0" the validation step is skipped. I would point out to you "eval_metric_for_imputation", "boot_test_perc", and "output_options" arguments are irrelevant in this case. Since you removed species with less than 10 occurrences, you should opt for boot_rep >0 in order to assess the accuracy of models.

Cheers,

**Comment by ggrittz** [comment]
Sorry I took some time to answer.

I adapted my presence-absence script and forgot about the issue of background points being sampled on presences...thank you. I'll use ```randomPoints``` from ```dismo``` to deal with this. Regarding raster/terra, I'm already adapting too. I was using boot_rep = 0 just to see if everything is working properly, my final run will have boot = 100 or 999 (depending on the lab's computer). 

Thanks again! I'll close this issue for now. If anything, I can create a new thread.
