### ISSUE TITLE
Unable to ENphylo_prediction() on the same data

### ISSUE THREAD

**Issue by ggrittz** [pasraia/RRdtn#2]
Hello again,

I finished modeling with ```ENphylo_modeling``` following your recommendations (thanks!) but now I'm having some issues related to predicting the models. 

I get an error related to variable names being different between ```newdata``` and the calibrated model, but I'm predicting the same data.

```
PREDICTING ENFA/IMPUTATION 
  |                                                  | 0 % ~calculating  Error in FUN(X[[i]], ...) : 
  Variable names in newdata must match with those used to calibrate models
```

Also, when I try to model a single species I get the following:

```
PREDICTING ENFA/IMPUTATION 
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=02s  

 CONVERTING PREDICTED VALUES TO SUITABILITY 
  |                                                  | 0 % ~calculating  
 Abarema_langsdorffii 
Error in data.frame(ID = 1:nrow(pred_for_th), observed = obs_background$OBS,  : 
  arguments imply differing number of rows: 5403, 0
```

Here are the files I used for modeling and the output of ```ENphylo_modeling```: https://drive.google.com/drive/folders/1Hz91FqoyPvP8HWq62AOtq_PCe9AsEnAy?usp=sharing

A fast read.me: 
```all_list.rds``` is the species list with occurrence, variables, and geometry;
```newraster.rds``` is a RasterStack of variables
```sample.tre``` is the phylogenetic tree
```raremod.rds``` is the output of ```ENphylo_modeling```

Below is the portion of the code related to the package

```
#Modeling
raremod <- ENphylo_modeling(input_data = all_list,
                            tree = tree,
                            input_mask = newraster[[1]],
                            obs_col = "occurrence",
                            min_occ_enfa = 20,
                            boot_test_perc = 20,
                            boot_reps = 100,
                            eval_metric_for_imputation = "AUC",
                            output_options = "best",
                            clust = 6,
                            eval_threshold = 0.5)
#saveRDS(raremod, "rds/raremod.rds")

#Predicting
raremod_pred <- ENphylo_prediction(object = raremod[1], #using the full raremod also doesn't work, as I quoted above
                                   newdata = newraster,
                                   calc_method = "terra",
                                   convert.to.suitability = TRUE)
```

I think you already have permission on the folder. Thanks again!

**Comment by pasraia** [comment]
Hi Guillherme,
We ran ENphylo on your data. Unfortunately, ENphylo_prediction gives an error due to mismatch between variable names and SpatRaster names (it's always perilous using the dash mark '-' within variable names in R). We fixed the incorrect syntax adopted by ENphylo to format row/column names with strange or uncommon symbols (i.e. the dash in our case). Thank you for reporting this issue, which is now resolved with the new release.
As minor points, we'd suggest you to calibrate ENphylo with a reduced number of variables in order to cure multicollinearity.  Although ENFA works on similar PCA space, all the specialization axes are orthogonal to the marginality axis, but not to each other. Moreover, please consider that the 'clust' argument specifies the proportion of cores to make enable, not their number.

Lastly, we are pleased to inform you last version of ENphylo is perfectly able to work with 'sf' and 'SpatRaster' objects. In addition, the function saves the single ENFA/impute models according to the directory path in order to facilitate the manipulation of outputs. We hope these new upgrades will help you to perform your analyses.

**Comment by ggrittz** [comment]
Hello,
Thank you again for the quick answer, as always. At the time, I opened a thread in StackExchange about the case of naming rasters using ```raster``` package. The user @Spacedman talked about the restriction of using a minus signal in names while using ```raster``` package and how this restriction is lifted on ```terra```. [Here's the link, if you're interested](https://gis.stackexchange.com/questions/452304/changing-the-names-of-a-rasterstack). 

**Related to calibrating ENphylo**—An statistical question now: I do have a set of already-orthogonal variables available that I can use (On prior analyses I performed a PCA on the same 23 variables and extracted the first five axes to use as predictors). Does the fact of these PCA-axes already being orthogonal a problem for ENFA? This was the reason I didn't use them before — and I had no one to ask.
 
**Related to 'clust'**—check.

Thank you once for being so available in answering. I'll test everything and give feedback asap.
