### ISSUE TITLE
Missing or not-matching projections in input data or background area

### ISSUE THREAD

**Issue by ggrittz** [pasraia/RRdtn#3]
Hello, it's me again

Sorry for bothering again. I took some time to post this here to check if I didn't do anything wrong with my data to avoid making you guys waste time. Below is the code I'm using to run this section (as always, I'll attach the data too).

```
#Loading species list
all_list <- readRDS("rds/all_list_enfa.rds")

#Loading predictors' extent/mask
preds <- readRDS("rds/predictors_df.rds")
preds <- rast(preds)
crs(preds) <- NA
#The crs below also doesn't work
#crs(preds) <- "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"

#Loading phylogenetic tree
tree <- ape::read.tree("sample.tre")

#Adjusting input data to sf::data.frame format
for(i in names(all_list)){
     all_list[[i]] <- st_as_sf(x = all_list[[i]],
                               coords = c("x", "y"),
                               crs = crs(preds[[1]]))
                         }

#Modeling ENphylo
raremod <- ENphylo_modeling(input_data = all_list,
                            tree = tree,
                            input_mask = preds[[1]],
                            obs_col = "occurrence",
                            min_occ_enfa = 20,
                            boot_test_perc = 20,
                            boot_reps = 100,
                            eval_metric_for_imputation = "AUC",
                            output_options = "best",
                            clust = 1,
                            eval_threshold = 0.5)
```

After running ```ENphylo_modeling``` I'm getting the ```Error in DATA_PREPARATION(species_input_data = data, obs_col = obs_col,  : 
  some missing or not-matching projections in input data or background area```. I really don't know what could be happening since I'm applying the same ```crs``` before for both the list objects and the mask. I looked at the code for ```DATA_PREPARATION``` and also didn't find a good reason there. For example, on line 10 of ```DATA_PREPARATION``` ```!crs(preds[[1]], proj = TRUE) == st_crs(all_list$Abarema_langsdorffii)$proj4string |
     is.na(crs(preds[[1]], proj = TRUE)) | is.na(st_crs(all_list$Abarema_langsdorffii)$proj4string)``` equals ```TRUE``` here (Abarema langsdorffii is the first species to be modeled). The only thing I changed was the function I'm using to sample pseudo-absences. I was using ```dismo::randomPoints``` but the function also samples pseudo-abences on presence cells, so now I'm using ```predicts::backgroundSample```. They are pretty much equal with the exception that I can restrict sampling pseudo-absences on presence cells. Apart from that, everything is equal.

![image](https://user-images.githubusercontent.com/45982618/222747006-34b8995c-4fc5-4257-879a-c8d47b6f2c9c.png)
Here's an idea of how I'm sampling pseudo-absences (all cells except from presence cells, since my study area is kinda small)

Here's the data for reproduction: https://drive.google.com/drive/folders/11LfowwyFOP6BjoGwmGu6QXj6SNtU_iXx?usp=share_link

**Comment by pasraia** [comment]
Hi Guillherme,
we suppose the pseudo-absence sampling approach is in conflict with the ENFA workflow. ENFA requires to export the entire background area in order to match both datapoints and background cells. ENFA is a presence-based SDM not and as such it does not rely on presence-pseudoabsence. Your data are wrongly formatted to work with ENFA. You may verify this on your own running the following lines:

extract(preds[[1]],subset(all_list$Abarema_langsdorffii,occurrence==1),cell=T)$cell->ones
extract(preds[[1]],subset(all_list$Abarema_langsdorffii,occurrence==0),cell=T)$cell->zeros
ones%in%zeros ### there is no correspondence between 0 and 1

As you will see, there is mismatching between data points and background cells. Please ensure the presence points overlay background points before starting ENphylo. 
regards

**Comment by ggrittz** [comment]
Ok, I see. Thank you again.
