### ISSUE TITLE
raster and terra conflict in environmentspace

### ISSUE THREAD

**Issue by ZMgogo** [pasraia/RRdtn#4]
When I run the following script,
Test 1 imputation of one species at a time.R
I get the error
unable to find an inherited method for function ‘extract’ for signature ‘"RasterLayer", "SpatVector"
It maybe the ENphylo_modeling in RRdtn has space issue. I try to change terra::extract by fork from GitHub, but not work!
I don't konw it only happen in my machine or others have met it

I appreciate the author's efforts

**Comment by pasraia** [comment]
Hi Zhu,

Please notice "Test 1.R" was meant to replicate the statistical analyses described in the MEE paper. After the publication, we released a new version of the RRdtn package on GitHub (0.5.4). The latter relies on “terra” and “sf” instead of “raster” and “sp” R packages. In addition, we partially modified R codes in order to provide other improvements. We recommend not to run the new 0.5.4 RRdtn version on input data embedded in the Dropbox folder. If you wish otherwise, you have to rely on the older version of the package. 
Please, do not hesitate to contact us again if you need further assistance.
cheers

**Comment by ZMgogo** [comment]
Thanks for your help.

**Comment by ZMgogo** [comment]
Thanks for your help. Your reply solved my issue. I'm running an incompatible version of code before. 
And now I tried with example code, and it seems to be working as expected.

In MEE paper, the occurrences data was from fossil. However, in my actual analysis, I only has occurrences no more than 200 years ago. I call it baseline (current) point, I wonder whether I can use ENphlyo to do my analysis.

cheers
