### ISSUE TITLE
Error happen when setting time_col as NULL

### ISSUE THREAD

**Issue by dru1889** [pasraia/RRdtn#7]
Hi, 

Thanks for your fixing the code.

BTW, can you figure out if I want to set up the time_col as NULL. what other parameters or input_data should be formatted? I set it as NULL, and use "Rangifer_tarandus" data to run ENphylo_modeling, then the error shows as "Error in colMeans(x, na.rm = TRUE) : 'x' must be numeric". 

Could you please help on this?

Cheers

dru1889

**Comment by pasraia** [comment]
Hi dru1889,
please could you provide the R code you used? 
Specifically, i need to say the ENphylo_modeling setting in order to reproduce/fix the error.

Regards,
Pas

**Comment by dru1889** [comment]
Thanks for your quick response:

Here is what I am using now:
------------------------------------------------------------------------------
load("ENphylo code&data/example_data.RData")

require(RRdtn)
source("ENphylo code&data/ecospat.ESM.EnsembleModeling_CUSTOM.R")
source("ENphylo code&data/ecospat.ESM.Projection_CUSTOM.R")
source("ENphylo code&data/ecospat.ESM.Modeling_CUSTOM.R")

MASK_FULL<-terra::rast("ENphylo code&data/variable_bio1.tif")

k=25
npoints=10  
Sys.setenv(LANG = "en")

ENmod<-ENphylo_modeling(input_data=DATA_FULL[k],
                         tree=tree,
                         input_mask=MASK_FULL,
                         obs_col="OBS",
                         time_col=NULL,                         
                         min_occ_enfa=npoints-1,
                         eval.args=list(eval_metric_for_imputation="AUC",
                                        output_options="best",
                                        eval_threshold=0.5))

------------------------------------------------------------------
the output is like:

_Warning: [extract] transforming vector data to the CRS of the rasterWarning: 154 duplicated points into raster cells were found and removed!Error in colMeans(x, na.rm = TRUE) : 'x' must be numeric_


Thanks  so much

**Comment by pasraia** [comment]
Hi dru,
I run ENphylo_modeling by replicating your approach. The issue  arises because the function is not designed to remove the time column from the native data if you set "time_col"=NULL. I kindly invite you to remove the "TIME_factor" column from the data before running ENphylo_modeling, This should fix it.

Ps= the following lines were not linked to ENphylo, so you can skip them:
source("ENphylo code&data/ecospat.ESM.EnsembleModeling_CUSTOM.R")
source("ENphylo code&data/ecospat.ESM.Projection_CUSTOM.R")
source("ENphylo code&data/ecospat.ESM.Modeling_CUSTOM.R")

Regards,
Alessandro Mondanaro

**Comment by dru1889** [comment]
Thanks for your advice and it works now :-)

**Comment by pasraia** [comment]
Thanks Dru, It was a pleasurePasOn Sep 7, 2024 14:50, dru1889 ***@***.***> wrote:
Closed #7 as completed.
